# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- feature/du/unit_module_testing

pool:
  vmImage: 'windows-latest'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'BebeOr3'
    testProjectPath: '$(Build.SourcesDirectory)\DocumentUnderstandingProcess\contentFiles\any\any\pt0\VisualBasic'
    folderName: 'Sales'
    traceLevel: 'Verbose'
    attachRobotLogs: true