trigger:
  batch: true
  branches:
    include:
    - develop
    - master/DocumentUnderstandingProcess*
  paths:
    include:
    - DocumentUnderstandingProcess/*
    - .pipelines/*

pr: none
  # branches:
  #   include:
  #   - develop
  #   - master/DocumentUnderstandingProcess*
  # paths:
  #   include:
  #   - DocumentUnderstandingProcess/*
  #   - .pipelines/*
  #   - azure-pipelines-DocumentUnderstandingProcess.yml

variables:
  - template: ../variables/common.yml
  - name: projectPath
    value: 'DocumentUnderstandingProcess'
  - name: projectNuspec
    value: 'UiPath.Template.DocumentUnderstandingProcess.nuspec'

jobs:
  - job: Tests
    steps:
      - task: DownloadPackage@1
        inputs:
          packageType: 'nuget'
          feed: '5b98d55c-1b14-4a03-893f-7a59746f1246/1c781268-d43d-45ab-9dfc-0151a1c740b7'
          view: 'ff65a51c-1b82-4f66-b9e7-0f06862b5527'
          definition: 'cfbaef4d-30cf-4387-817a-c5ee1000778b'
          version: '1.0.8136.25036'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: UiPathInstallPlatform@2
        displayName: 'Install platform to cache internal tool'

      # Override UIPCLI with one that supports running tests from a nupkg
      - powershell: |
          Get-ChildItem $env:UIPCLIDirectory -Directory -ErrorAction Ignore | ForEach-Object -Process {
            $destination = [System.IO.Path]::Combine($_.FullName, "x64")
            Write-Host $("Copy to " + $destination)
            Copy-item -Force -Recurse -Verbose $env:Source -Destination $destination
          }
        displayName: "Override UiPath CLI version"
        env:
          Source: "$(Build.SourcesDirectory)\\uipcli\\*"

      - task: UiPathTest@2
        inputs:
          testTarget: 'TestProject'
          orchestratorConnection: 'BebeOr3'
          testProjectPath: '$(Build.SourcesDirectory)'
          folderName: 'Sales'
          traceLevel: 'Verbose'
          attachRobotLogs: true


  - template: ../jobs/ci.yml
    parameters: 
      projectPath: ${{ variables.projectPath }}
      projectNuspec: ${{ variables.projectNuspec }}

